var data = [
    {
        'id': 1 ,
        'name': 'đồng hồ tư bản',
       'price': 2000000 ,
       'sale': 15000000,
       'category': 'đồng hồ châu âu',
       'image' : 'w1.png',
       'star': 1,
       'hotdeal': 1,
    },
    {
        'id': 2 ,
        'name': 'đồng hồ tư bản',
       'price': 2000000 ,
       'sale': 15000000,
       'category': 'đồng hồ châu âu',
       'image' : 'w1.png',
       'star': 1,
       'hotdeal': 1,
    },
    {
        'id': 3 ,
        'name': 'đồng hồ tư bản',
       'price': 2000000 ,
       'sale': 15000000,
       'category': 'đồng hồ châu âu',
       'image' : 'w1.png',
       'star': 1,
       'hotdeal': 1,
    },
    {
        'id': 4 ,
        'name': 'đồng hồ tư bản',
       'price': 2000000 ,
       'sale': 1000000,
       'category': 'đồng hồ châu á',
       'image' : 'w4.png',
       'star': 1,
       'hotdeal': 2,
    },
    {
        'id': 5 ,
        'name': 'đồng hồ tư bản',
       'price': 2000000 ,
       'sale': 1000000,
       'category': 'đồng hồ châu á',
       'image' : 'w4.png',
       'star': 1,
       'hotdeal': 2,
    },
    {
        'id': 6 ,
        'name': 'đồng hồ tư bản',
       'price': 2000000 ,
       'sale': 1000000,
       'category': 'đồng hồ châu á',
       'image' : 'w4.png',
       'star': 1,
       'hotdeal': 2,
    },
    {
        'id': 7 ,
        'name': 'đồng hồ tư bản',
       'price': 2000000 ,
       'sale': 15000000,
       'category': 'đồng hồ châu phi',
       'image' : 'w3.png',
       'star': 1,
       'hotdeal': 3,
    },
    {
        'id': 8 ,
        'name': 'đồng hồ tư bản',
       'price': 2000000 ,
       'sale': 15000000,
       'category': 'đồng hồ châu phi',
       'image' : 'w3.png',
       'star': 1,
       'hotdeal': 3,
    },
    {
        'id': 9 ,
        'name': 'đồng hồ tư bản',
       'price': 2000000 ,
       'sale': 15000000,
       'category': 'đồng hồ châu phi',
       'image' : 'w3.png',
       'star': 1,
       'hotdeal': 3,
    },
]